services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: movdb
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d movdb"]
      interval: 5s
      timeout: 3s
      retries: 10

  app:
    build: ./app
    environment:
      DB_DSN: postgresql+psycopg://app:app@db:5432/movdb
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"

volumes:
  db_data:
